# Generated by Django 5.1.1 on 2025-01-21 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="ยืนยันแล้วหรือไม่"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="website",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="เว็บไซต์/โซเชียลมีเดีย",
            ),
        ),
    ]
