# Generated by Django 5.1.1 on 2025-01-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_seller_is_verified_alter_seller_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
