# Generated by Django 5.1.1 on 2025-01-21 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_seller_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="email",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="password",
        ),
    ]
