# Generated by Django 5.1.1 on 2025-01-22 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_seller_email_remove_seller_last_login_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(max_length=255, verbose_name="ประเภทผิว"),
                ),
                ("concern", models.TextField(verbose_name="ปัญหาผิวหน้า")),
                (
                    "allergy_history",
                    models.TextField(
                        blank=True, null=True, verbose_name="อาการแพ้หรือปัญหาที่พบ"
                    ),
                ),
                (
                    "current_products",
                    models.TextField(
                        blank=True, null=True, verbose_name="ผลิตภัณฑ์ที่ใช้ปัจจุบัน"
                    ),
                ),
                (
                    "skincare_goal",
                    models.TextField(
                        blank=True, null=True, verbose_name="เป้าหมายการดูแลผิวหน้า"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่ส่งข้อมูล"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skin_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpertResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField(verbose_name="คำตอบจากผู้เชี่ยวชาญ")),
                (
                    "responded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่ตอบกลับ"
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skin_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_response",
                        to="accounts.skindata",
                    ),
                ),
            ],
        ),
    ]
