# Generated by Django 5.1.1 on 2025-01-24 07:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_skindata_expertresponse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertresponse",
            name="responded_at",
        ),
        migrations.AddField(
            model_name="expertresponse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skindata",
            name="skin_image",
            field=models.ImageField(blank=True, null=True, upload_to="skin_images/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อหมวดหมู่"),
        ),
        migrations.AlterField(
            model_name="expertresponse",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expert_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expertresponse",
            name="response",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="expertresponse",
            name="skin_data",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response",
                to="accounts.skindata",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="skindata",
            name="allergy_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skindata",
            name="concern",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="skindata",
            name="current_products",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skindata",
            name="skin_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="skindata",
            name="skincare_goal",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skindata",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="skinupload",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skin_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
