# Generated by Django 5.1.1 on 2025-01-26 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_expertresponse_responded_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expertresponse",
            old_name="response",
            new_name="response_text",
        ),
    ]
