# Generated by Django 5.1 on 2024-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_age_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Member', 'Member'), ('Admin', 'Admin'), ('Expert', 'Expert')], default='User', max_length=10),
        ),
    ]
