# Generated by Django 5.1.1 on 2025-01-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_expertreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="expertresponse",
            name="skin_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="accounts.skindata",
            ),
        ),
    ]
