# Generated by Django 5.1.1 on 2024-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_review_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("license_number", models.CharField(max_length=255)),
                ("expertise", models.CharField(max_length=255)),
                ("workplace", models.CharField(max_length=255)),
                ("experience", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
