# Generated by Django 5.1.1 on 2025-02-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_expertresponse_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skindata",
            name="skin_image",
        ),
        migrations.AlterField(
            model_name="skindata",
            name="concern",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skindata",
            name="skin_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="SkinImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="skin_images/")),
                (
                    "skin_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="accounts.skindata",
                    ),
                ),
            ],
        ),
    ]
