# Generated by Django 5.1.1 on 2024-12-13 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="address",
        ),
    ]
