# Generated by Django 5.1.1 on 2025-02-11 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_expertarticle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertarticle",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="expertarticle",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="expertarticle",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expertarticle",
            name="how_to_check",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expertarticle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
        migrations.AlterField(
            model_name="expertarticle",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="expertarticle",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="expertarticle",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
