# Generated by Django 5.1.1 on 2024-12-18 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_remove_seller_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expert",
            name="email",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="password",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="username",
        ),
        migrations.AddField(
            model_name="expert",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expert_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expert",
            name="user_temp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="expert",
            name="experience",
            field=models.TextField(verbose_name="ประสบการณ์การทำงาน"),
        ),
        migrations.AlterField(
            model_name="expert",
            name="expertise",
            field=models.CharField(max_length=100, verbose_name="ความเชี่ยวชาญ"),
        ),
        migrations.AlterField(
            model_name="expert",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="ชื่อ-สกุล"),
        ),
        migrations.AlterField(
            model_name="expert",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="ยืนยันแล้ว"),
        ),
        migrations.AlterField(
            model_name="expert",
            name="license_number",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="เลขใบประกอบวิชาชีพ"
            ),
        ),
        migrations.AlterField(
            model_name="expert",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="experts/profile_images",
                verbose_name="รูปโปรไฟล์",
            ),
        ),
        migrations.AlterField(
            model_name="expert",
            name="workplace",
            field=models.CharField(max_length=100, verbose_name="สถานที่ทำงาน"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
