# Generated by Django 5.1.1 on 2025-02-13 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_expertarticle_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification_level", models.CharField(max_length=50)),
                ("average_rating", models.FloatField()),
                ("total_reviews", models.PositiveIntegerField()),
                ("issue_date", models.DateField(auto_now_add=True)),
                (
                    "expert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
