# Generated by Django 5.1.6 on 2025-03-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="certification_level",
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
