# Generated by Django 5.1.6 on 2025-03-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_remove_certificate_certification_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Mask", "sohk"),
                    ("oily", "ผิวมัน"),
                    ("dry", "ผิวแห้ง"),
                    ("combination", "ผิวผสม"),
                    ("sensitive", "ผิวแพ้ง่าย"),
                ],
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
