# Generated by Django 5.1.1 on 2025-01-06 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_remove_expert_user_temp_product_added_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="business_name",
            field=models.CharField(max_length=255, verbose_name="ชื่อธุรกิจ"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="วันที่สมัครสมาชิก"
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="อีเมล"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="ชื่อ-สกุล"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="product_category",
            field=models.CharField(max_length=255, verbose_name="หมวดหมู่สินค้า"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="product_samples",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="seller_product_samples/",
                verbose_name="ตัวอย่างสินค้า",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="seller_profiles/",
                verbose_name="รูปโปรไฟล์",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="website",
            field=models.URLField(
                blank=True, null=True, verbose_name="เว็บไซต์/โซเชียลมีเดีย"
            ),
        ),
    ]
