# Generated by Django 5.1.1 on 2025-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_expert_phone_number_seller_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="password",
            field=models.CharField(default=1, max_length=128, verbose_name="รหัสผ่าน"),
            preserve_default=False,
        ),
    ]
