# Generated by Django 5.1.6 on 2025-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_rename_added_by_product_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
