# Generated by Django 5.1.6 on 2025-03-27 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_alter_profile_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user_id",
            new_name="user",
        ),
    ]
