# Generated by Django 5.1.6 on 2025-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_rename_user_id_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="skindata",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="skin_data"),
        ),
    ]
