# Generated by Django 5.1.6 on 2025-03-28 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_skindata_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="user_id",
        ),
    ]
