# Generated by Django 5.1.6 on 2025-03-28 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_rename_user_product_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user_id",
            new_name="user",
        ),
    ]
